[connections.snowpark]
user = "bhill"
password = "Carlisbigandsmelly#1"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "SFSENORTHAMERICA-DEMO_BHILL"

# .streamlit/secrets.toml
OPENAI_API_KEY = "sk-2v...X"
